platform :ios do
  
  desc "Get certificates"
  lane :certificates do
    sync_code_signing(
      type: "development",
      app_identifier: ['dev.shorebird.fastlane_demo'],
      force_for_new_devices: true,
      readonly: true
    )

    sync_code_signing(
      type: "appstore",
      app_identifier: 'dev.shorebird.fastlane_demo',
      readonly: true
    )
  end

  desc "Generate new certificates"
  lane :generate_new_certificates do
    sync_code_signing(
      type: "development",
      app_identifier: ['dev.shorebird.fastlane_demo'],
      force_for_new_devices: true,
      readonly: false
    )
  end
end