platform :ios do
  
  desc "Get certificates"
  lane :certificates do
    sync_code_signing(
      type: "development",
      app_identifier: ['dev.shorebird.fastlane-demo'],
      force_for_new_devices: true,
      readonly: true
    )

    sync_code_signing(
      type: "appstore",
      app_identifier: 'dev.shorebird.fastlane-demo',
      readonly: true
    )
  end

  desc "Generate new certificates"
  lane :generate_new_certificates do
    sync_code_signing(
      type: "development",
      app_identifier: ['dev.shorebird.fastlane-demo'],
      force_for_new_devices: true,
      readonly: false
    )
    sync_code_signing(
      type: "appstore",
      app_identifier: 'dev.shorebird.fastlane-demo',
      force_for_new_devices: true,
      readonly: false
    )
  end

  desc "deploy"
  lane :deploy do
    setup_ci
    sync_code_signing(
      type: "appstore",
      app_identifier: 'dev.shorebird.fastlane-demo',
      readonly: true
    )
    build_app(
      scheme: "Runner",
      export_options:{ 
        manageAppVersionAndBuildNumber: false 
      }
    )
    app_store_connect_api_key(
      is_key_content_base64: true,
      in_house: false, # if it is enterprise or not
    )
    upload_to_app_store(
      force: false,
      precheck_include_in_app_purchases: false,
      run_precheck_before_submit: true,
      submit_for_review: false
    )
  end
end